import {
  ADMIN_CRYPTIC_ACTIVIST_CATALOG,
  CHAT_API_ENDPOINT,
  CRYPTIC_ACTIVIST_CATALOG,
  CRYPTOCURRENCY_API_ENDPOINT,
  FIAT_API_ENDPOINT,
  NEW_CRYPTIC_ACTIVIST_CATALOG,
  OFFER_API_ENDPOINT,
  TRADE_API_ENDPOINT,
  USER_API_ENDPOINT,
} from '../../../constants/envs';

export default {
  origin: [
    CHAT_API_ENDPOINT,
    CRYPTOCURRENCY_API_ENDPOINT,
    FIAT_API_ENDPOINT,
    OFFER_API_ENDPOINT,
    TRADE_API_ENDPOINT,
    USER_API_ENDPOINT,
    CRYPTIC_ACTIVIST_CATALOG,
    ADMIN_CRYPTIC_ACTIVIST_CATALOG,
    NEW_CRYPTIC_ACTIVIST_CATALOG,
  ] as string[],
};
